### PR TITLE
Migrate during provision

### PR DESCRIPTION
**Pull request by xmunoz**

### CODE REVIEW

**Comment by jasonaowen** [comment]
This looks good to me! Thanks for doing this, @xmunoz.

I'm afraid I don't have the bandwidth to test this right now; @mithuna would you mind?

**Comment by mithuna** [comment]
@xmunoz To test this  I need to do a destroy up of my vagrant right?

**Comment by xmunoz** [comment]
Yeah, probs, since you want to ensure that the db migration is successfully run. Alternatively, you could roll back to an old db version and verify that the migration applied the expected changed, but I don't know to rollback a migration byjg

**Review by mithuna — APPROVED** [review]
Migrations ran on vagrant up.

**Pull request merged**
