### PR TITLE
Update local environment to use Debian 12

### PR DESCRIPTION
**Pull request by liam-lloyd**

### CODE REVIEW

**Review by cecilia-donnelly — COMMENTED** [review]
I tried this with the corresponding infrastructure change and still got stuck at the SSH authentication step:

```    
permanent: SSH auth method: private key
permanent: Warning: Authentication failure. Retrying...
```

Not sure what's going on but that's the current status.

**Comment by liam-lloyd** [comment]
> I tried this with the corresponding infrastructure change and still got stuck at the SSH authentication step:
> 
> ```
> permanent: SSH auth method: private key
> permanent: Warning: Authentication failure. Retrying...
> ```
> 
> Not sure what's going on but that's the current status.

I've double checked to see if I could reproduce this, but to no avail.

**Review by meisekimiu — APPROVED** [review]
I was able to get the devenv running with Debian 12 without the ssh issues.

**Comment by cecilia-donnelly** [comment]
Thanks for testing @meisekimiu !

**Pull request merged**
