### PR TITLE
helper script to sync all repos

### PR DESCRIPTION
**Pull request by Fenn-CS**
This script syncs across "all" main repo's required by the devenv

### CODE REVIEW

**Comment by xmunoz** [comment]
Can you move this script into bin, and add information about it to the README?

**Comment by Fenn-CS** [comment]
Sure!

**Comment by cecilia-donnelly** [comment]
Can you add https://github.com/PermanentOrg/notification-service ?  It might also need to be added to the README, since presumably that's where you sourced the list of necessary repos.

**Comment by jasonaowen** [comment]
Note that we do not run the notification service inside of vagrant, per https://github.com/PermanentOrg/devenv/issues/12#issuecomment-778444819 .

**Comment by Fenn-CS** [comment]
So what's the conclusion?

**Comment by cecilia-donnelly** [comment]
Can you update the README to include the notification service?  It doesn't need to be in the script - I forgot that we run it outside the VM.  Thanks!

**Comment by cecilia-donnelly** [comment]
@Fenn-CS Please add the notification-service to the required repos listed in the README.

**Review by cecilia-donnelly — APPROVED** [review]
Thanks!

**Pull request merged**
