### PR TITLE
Change location of seed file

### PR DESCRIPTION
**Pull request by xmunoz**
- Remove references to the docker repository

### CODE REVIEW

**Comment by jasonaowen** [comment]
Thanks for working on this, @xmunoz!

It looks like this PR has an alternate version of 7d36d47833e42bca35ab261715a081b49f5f7ccc, merged in PR #30. Can you please rebase that away?

More importantly, can we use the new reset migration script instead of manually touching MySQL?

**Comment by xmunoz** [comment]
> More importantly, can we use the new reset migration script instead of manually touching MySQL?

That would be complicated because that dump creates the database and the user with credentials to access it. What would be the benefit of using the migration?

**Comment by jasonaowen** [comment]
That we're using the same method in local as we are in CI, and that we slightly disentangle the local environment configuration from the application. Part of the point of the migration tool is to be more agnostic about the database.

> That would be complicated because that dump creates the database and the user with credentials to access it.

Can you say more about this complication? Isn't that what the migration script is doing?

**Comment by xmunoz** [comment]
> Can you say more about this complication? Isn't that what the migration script is doing?

The CI is using a mysql image that has the option to configure a password-less database at startup. That is how the init script is able to connect and run. It's not clear how to do this with the current mysql install on this VM. Feel free to push to this branch directly though if you'd like to work on that.

> Part of the point of the migration tool is to be more agnostic about the database.

I think this is a nice idea, but there will need to be significant infrastructure changes to be able move to a different db. If we find a need to do that, I can move this over at that time.

**Review by cecilia-donnelly — APPROVED** [review]
I was able to bring up a local environment from this branch after doing a `vagrant destroy`.  Thanks, @xmunoz !  In fact, currently this branch is required because the database seed file has already been moved in the `docker` repo.

**Pull request merged**
